version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - searchnet

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - searchnet

networks:
  searchnet:
    driver: bridge
